[package]
name = "huixin"
version.workspace = true
edition.workspace = true
authors.workspace = true
build = "build.rs"

[build-dependencies]
chrono = "0.4"

[dependencies]
# EGUI
eframe = { workspace = true, features = ["default"] }
egui = { workspace = true }
ecolor = { workspace = true }
emath = { workspace = true }
egui_extras = { workspace = true }
# Logging
log = { workspace = true }
simplelog = { workspace = true }
# Concurrency
parking_lot = "0.12"
dashmap = { version = "7.0.0-rc2" }
rayon = "1.11"
# Communication
serde = { workspace = true }
ron = { workspace = true }
# Misc
either = "1.15"
lyn-util = { workspace = true }
