[package]
name = "huixin"
version.workspace = true
edition.workspace = true
authors.workspace = true
build = "build.rs"

[build-dependencies]
chrono = "0.4"

[dependencies]
# EGUI
eframe = { workspace = true, features = ["default"] }
egui = { workspace = true }
emath = { workspace = true }
# Logging
log = { workspace = true }
simplelog = { workspace = true }
# Concurrency
parking_lot = "0.12"
dashmap = "7.0.0-rc2"
# Misc
lyn-util = { workspace = true }
